baseURL = 'https://lourkeur.github.io/'
languageCode = 'en-us'
title = "Louis Bettens' Homepage"
theme = 'PaperMod'

[security.exec]
allow = ['^rst2html$']

[params.profileMode]
enabled = true
title = "Louis Bettens"
imageUrl = "/avi.png"
imageTitle = "silly profile picture of a Nix logo with cat features"

[[params.profileMode.buttons]]
name = "Blog"
url = "/blog"


[[params.socialIcons]]
name = "github"
url = "https://github.com/lourkeur"

[[params.socialIcons]]
name = "email"
url = "mailto:louis@bettens.info"

[[params.socialIcons]]
name = "cv"
url = "/cv"

[[params.socialIcons]]
name = "pgpkey"
url = "/pgpkey"

[[params.socialIcons]]
name = "keybase"
url = "https://keybase.io/lourkeur"

[[params.socialIcons]]
name = "matrix"
url = "https://matrix.to/#/@lourkeur:nixos.dev"

[[params.socialIcons]]
name = "reddit"
url = "https://reddit.com/user/lourkeur"

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/lourkeur"
